fix: 1

diff --git a/.github/workflows/acme-lab.yml b/.github/workflows/acme-lab.yml
--- a/.github/workflows/acme-lab.yml
+++ b/.github/workflows/acme-lab.yml
@@ -26,7 +26,7 @@ jobs:
       - name: Step 1.3 name
         id: step-1-3
         shell: sh
-        run: echo "some_output=$MESSAGE_ID" >> $GITHUB_OUTPUT
+        run: echo "some_output='Ya ma7leha ya baba ya 7anni'" >> $GITHUB_OUTPUT
       - name: Step 1.4 name
         id: step-1-4
         shell: bash
@@ -91,17 +91,9 @@ jobs:
         shell: bash
         run: |
           echo "TEST failure()";
-          if [ failure() ]; then
-            echo "FAILURE";
-          else
-            echo "SUCCESS";
-          fi
+          failure() && echo "FAILURE" || echo "SUCCESS";
 
           echo "TEST success()"
-          if [ success() ]; then
-            echo "SUCCESS";
-          else
-            echo "FAILURE";
-          fi
+          success() && echo "SUCCESS" || echo "FAILURE";
 
           echo "END"
